version: '2'
services:
    enterprisearchitecture-app:
        image: enterprisearchitecture
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://enterprisearchitecture-mysql:3306/enterprisearchitecture?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    enterprisearchitecture-mysql:
        extends:
            file: mysql.yml
            service: enterprisearchitecture-mysql
